sizmailov/pybind11-stubgen

pybind11_stubgen/__init__.py

Now multiple newlines of 3+ don't return as true. Therefore empty docstrings of multiple newlines are added. This is fixed by this PR.

Add missing re.MULTILINE

---

pybind11_stubgen/__init__.py

Great tool. I had some issues running it on a large module (https://github.com/CadQuery/OCP). Here is the workaround.

Missing __module__ fix

---

pybind11_stubgen/__init__.py

- Fixes stubgen on Windows x64
From https://github.com/robotpy/robotpy-wpilib/runs/1132157020?check_suite_focus=true:
```
[2020-09-18 05:11:26,764] {__init__.py:92} ERROR - Generated stubs signature is degraded to `(*args, **kwargs) -> typing.Any` for
[2020-09-18 05:11:26,764] {__init__.py:96} ERROR - def __init__(self: wpilib.controller._controller.trajectory.TrapezoidProfile, constraints: wpilib.controller._controller.trajectory.TrapezoidProfile.Constraints, goal: wpilib.controller._controller.trajectory.TrapezoidProfile.State, initial: wpilib.controller._controller.trajectory.TrapezoidProfile.State = <wpilib.controller._controller.trajectory.TrapezoidProfile.State object at 0x0000016372EFFC38>) -> None: ...
[2020-09-18 05:11:26,764] {__init__.py:97} ERROR - …
```

Replace default values with uppercase in addition to lowercase hex values

---

pybind11_stubgen/__init__.py
test/stubs/expected/cpp_library_bindings/_core/issues/__init__.pyi

This PR removes common leading whitespace from multiline docstrings using [`inspect.cleandoc()`](https://docs.python.org/3/library/inspect.html#inspect.cleandoc).
For example:
```python
def issue_51(arg0: int, arg1: int) -> None:
"""
Use-case:
issue_51(os.get_handle_inheritable, os.set_handle_inheritable)
"""
```
becomes:
```python
def issue_51(arg0: int, arg1: int) -> None:
"""
Use-case:
issue_51(os.get_handle_inheritable, os.set_handle_inheritable)
"""
```
The example above is from the stubs generated by the existing test project, so it doesn't seem necessary to create any additional tests.
It's worth noting that `cleandoc()` also converts tabs to spaces and strips empty lines from either end of the docstring (which seems to be correct behaviour). However, if any of this additional …

Clean up docstring indentation

---

pybind11_stubgen/__init__.py

The typo was preventing `Union` from being converted to `typing.Union`.

Fix: Union regex typo

---

pybind11_stubgen/__init__.py

This PR allows for nested directories and improves the `DirectoryWalkerGuard` context manager.
The directory creation logic was not designed to handle nested output directories. It would still work if the nested directories were already present, but a `FileNotFoundError` would be raised if the nested subdirectories didn't exist. Additionally, the `DirectoryWalkerGuard` context manager would return to the parent directory after exiting (instead of the original working directory). This PR fixes these issues and also simplifies directory creation by allowing `DirectoryWalkerGuard` to create all directories.
These changes shouldn't modify any existing functionality, so all the current testing should still be relevant.

Add support for nested output directories

---

pybind11_stubgen/__init__.py

I detected that some attributes were being outputted as `<class CLASSNAME>`.
A quick look into the code showed that one line attributes used the method `fully_qualified_name` to output their typename, but, for multi-line ones, a simple `str(type(attr))` was used.
This pull request changes this behaviour to also use the `fully_qualified_name` on the multi-line ones.

Use fully qualified name for multi-line attributes

---

pybind11_stubgen/__init__.py

When generating stubs for pybind11 functions with default string arguments, the `_find_str_end `function is called.
While iterating over the argument string, it compares the index to the current character which will not work.
This PR fixes this by comparing the current character to the initial character instead.
Example pybind11 binding:
```
class MyClass
{
public:
void setAuthToken(std::string){};
};
py::class_<MyClass> myclass(m, "MyClass");
myclass.def("set_auth_token", &MyClass::setAuthToken, py::arg("token") = "somedefaultvalue");
```

fix function signature _find_str_end

---

pybind11_stubgen/__init__.py

Just extended the `repr` regex to support negative values on enumeration defaults.
Example:
```c++
enum enum_type {
VALUE = -1
};
py::enum_<enum_type>(m, "enum_type").value("VALUE", VALUE);
m.def("test_negative_value", [] (enum_type v) {}, py::arg("v") = VALUE);
```
When generating the example's stubs, pybind11-stubgen would return an error showing telling that the `test_negative_value` method has invalid signature.
This pull request fixes that kind of problem.

Allow negative values for enum defaults

---

pybind11_stubgen/__init__.py

Support for https://github.com/pybind/pybind11/pull/4158 if it ever gets merged. I don't see any harm in including this now -- any future classmethod implementations are going to follow the normal python convention of `cls` as the first argument.

Add support for @classmethod

---

pybind11_stubgen/__init__.py
setup.py
tests/pybind11-project-example/cpp_library_bindings/_core/cpp_library.cpp
tests/stubs/expected/cpp_library_bindings/_core/std_array/__init__.pyi

It was initially suggested in https://github.com/sizmailov/pybind11-stubgen/pull/99/files#diff-2b9c012912fd21677fba400f4b90573daf3a733b47c7912f88c1689c238402f9R372
Also this fixes mypy error (missing py.typed), because pybind11_stubgen.typing_ext is imported.

Corrected FixedSize property get signature

---

pybind11_stubgen/__init__.py
tests/stubs/expected/cpp_library_bindings/_core/opaque_types/__init__.pyi

Currently, `__hash__ = None` results in a type checking error because it's original type is not optional.
This PR changes that to `__hash__ = None # type: None` to force type checking to pass and the entire class is then correctly recognized as unhashable.

Add special type hinting for __hash__ to declare class as unhashable

---

pybind11_stubgen/parser/mixins/parse.py
tests/py-demo/demo/pure_python/__init__.py
tests/py-demo/demo/pure_python/classes.py
tests/stubs/demo/_bindings/classes.pyi
tests/stubs/demo/pure_python/__init__.pyi
tests/stubs/demo/pure_python/classes.pyi
tests/stubs/demo/pure_python/functions.pyi

Use only direct bases, exclude `object`

Fix base class list

---

.github/workflows/ci.yml
.gitignore
tests/check-demo-stubs-generation.sh
tests/install-demo-module.sh

- Split test scripts in two:
- `demo` module installation
-  stubs generation/check
- Generate `.patch` artifacts on failed CI jobs

chore: Imporve CI

---

pybind11_stubgen/__init__.py

The handling of submodules as the CLI argument was never perfect, but it got utterly broken in 1.0.
<details><summary>Compare tree structure in different versions</summary>
```text
VERSION: 👉 0.16
+ pybind11-stubgen module1.module2.module3
stubs
└── module1
└── module2
└── module3-stubs
├── __init__.pyi
└── setup.py
3 directories, 2 files
+ pybind11-stubgen module1.module2.module3 --root-module-suffix=
stubs
└── module1
└── module2
└── module3
├── __init__.pyi
└── setup.py
3 directories, 2 files
+ pybind11-stubgen module1.module2.module3 --root-module-suffix=-stubs
stubs
└── module1
└── module2
└── module3-stubs
├── __init__.pyi
└── setup.py
3 directories, 2 files
VERSION: 👉 pybind11-stubgen~=1.0
+ pybind11-stubgen module1.module2.module3
stubs
└── module3.pyi
0 directories, 1 file
+ …
```

fix: Missing subdirectories top-level submodules

---

README.md
pybind11_stubgen/__init__.py
pybind11_stubgen/writer.py

The option could be helpful for downstream doc-generation tools that expect `.py` files only.

Add `--stub-extension` CLI option

---

CHANGELOG.md
pybind11_stubgen/parser/mixins/fix.py
tests/demo-lib/include/demo/sublibA/ConsoleColors.h
tests/py-demo/bindings/src/modules/enum.cpp
tests/stubs/python-3.11/pybind11-master/demo/_bindings/enum.pyi
tests/stubs/python-3.7/pybind11-master/demo/_bindings/enum.pyi
tests/stubs/python-3.8/pybind11-master/demo/_bindings/enum.pyi

Fix enum value regexp

---

.github/workflows/ci.yml
pybind11_stubgen/parser/mixins/error_handlers.py
tests/check-demo-errors-generation.sh
tests/demo.errors.stderr.txt

Show function name in error message

---

pybind11_stubgen/__init__.py
pybind11_stubgen/parser/mixins/fix.py
pybind11_stubgen/printer.py
pybind11_stubgen/structs.py

I have a draft for #113, and these are some unrelated changes I made in preparation:
1. `CLIArgs` `argparse.Namespace` dataclass for improved type checking in `pybind11_stubgen/__init__.py`
2. not necessary to index `sys.version_info`, and doing so interferes with VS Code's reachability highlighting
3. ~~custom `all_isinstance` `TypeGuard` in `pybind11_stubgen/parser/mixins/fix.py` to resolve a type error in arguments to `FixedSize` vs `DynamicSize`~~
4. use `Sequence` to accept broader types
5. [typo in `FixMissingImport.handle_type`?](https://github.com/sizmailov/pybind11-stubgen/pull/186/files#diff-289d00b72d59bc6abd440cae1271bd3457346ab85a6b53b34c060f26662e482bL115)
6. use comprehension instead of `map`

style: 💄 typing improvements

---

pybind11_stubgen/parser/mixins/fix.py

When `--numpy-array-use-type-var` is specified and the parameter of `numpy.array` is `numpy.uint8`, it still generates `numpy.ndarray[numpy.uint8]`.

Add support for additional numpy data types

---

.github/workflows/ci.yml
CHANGELOG.md
setup.py

Publish of `v2.5.2` failed due to outdated `upload-artifact` 
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```

ci: bump version of upload-artifact

---

pybind11_stubgen/parser/mixins/parse.py
pybind11_stubgen/structs.py
pybind11_stubgen/writer.py

If a module has an `__path__` attribute it should be treated as a package even if it doesn't have any submodules.

Improve package detection

---

pybind11_stubgen/parser/mixins/parse.py

Pybind11 3 changed the holder for functions to a type starting with `pybind11_detail_function_record_`
Eg `pybind11_detail_function_record_v1_msvc_md_mscver19`
This breaks the old implementation.
This fix should fix all the cases.

Fix qualname prefix in pybind11 3.0.0
